#ifndef __GLOBALS_H__
#define __GLOBALS_H__
#endif
#define AUTO 0
#define BREAK 1
#define CASE 2
#define CHAR 3
#define CONST 4
#define CONTINUE 5 
#define DEFAULT 6
#define DO 7 
#define DOUBLE 8 
#define ELSE 9
#define ENUM 10
#define EXTERN 11
#define FLOAT 12
#define FOR 13
#define GOTO 14
#define IF 15 
#define INT 16 
#define LONG 17 
#define REGISTER 18
#define RETURN 19
#define SHORT 20
#define SIGNED 21
#define SIZEOF 22
#define STATIC 23 
#define STRUCT 24
#define SWITCH 25 
#define TYPEDEF 26 
#define UNION 27
#define UNSIGNED 28
#define VOID 29
#define VOLATILE 30
#define WHILE 31
#define CONSTANT 32
#define STRING_LITERAL 33
#define ELLIPSIS 34
#define RIGHT_ASSIGN 35
#define LEFT_ASSIGN 36
#define ADD_ASSIGN 37
#define SUB_ASSIGN 38
#define MUL_ASSIGN 39
#define DIV_ASSIGN 40
#define MOD_ASSIGN 41
#define AND_ASSIGN 42
#define XOR_ASSIGN 43
#define OR_ASSIGN 44
#define RIGHT_OP 45
#define LEFT_OP 46
#define INC_OP 47
#define DEC_OP 48
#define PTR_OP 49
#define AND_OP 50
#define OR_OP 51
#define LE_OP 52 
#define GE_OP 53
#define EQ_OP 54
#define NE_OP 55
#define EOI 56
#define OPEN_BRACKET 57
#define CLOSE_BRACKET 58
#define COMMA 59
#define COLON 60
#define ASSIGN 61
#define OPEN_ROUND_BRACKET 62
#define CLOSE_ROUND_BRACKET 63
#define OPEN_SQUARE_BRACKET 64
#define CLOSE_SQUARE_BRACKET 65
#define PERIOD 66
#define AND 67
#define NEGATE 68
#define NON 69
#define SUB 70
#define ADD 71
#define MUL 72 
#define DIV 73
#define MOD 74
#define LESSER 75
#define GREATER 76
#define XOR 77
#define OR 78
#define IDENTIFIER 79
#define TYPE_NAME 80
#define COND_OP 81
